RAW_DATA_DIR: './data/data_files/raw_data'
TRAIN_DATA_DIR: '../data/data_files/train'
DATASET:
  POLARISATION: ['HH']
  PREPROCESSING:
    DOWNSCALE_FACTOR: 2
    DECIMATION: True
    WINDOW: "hanning"
  CLIP:
    MIN: -200
    MAX: 0  
  IMAGE_SIZE: 250
  NUM_THREADS: 4
  BATCH_SIZE: 2
  VALID_RATIO: 0.2
TRAIN:
  CHECKPOINT_STEP: 5
  PRETRAINED:
    BOOL: True
    PATH: "../model_zoo/swinir/003_realSR_BSRGAN_DFO_s64w8_SwinIR-M_x4_PSNR.pth"
    STRICT : False
  LOSS :
    NAME: "l1"
    WEIGHT: 1
  OPTIMIZER:
    NAME: Adam
    CLIPGRAD: 0
    ADAM:
      WEIGHT_DECAY: 0
      LR_INITIAL: 0.001
  SCHEDULER:
    NAME: "MultiStep"
    MULTISTEP:
      STEPS: [200000, 400000, 600000, 800000, 1000000, 2000000]
      GAMMA: 0.5
  REGULARIZER:
    ORTHSTEP: 0
    CLIPSTEP: 0
  EPOCH: 50
  TENSORBOARD_DIR: 'tensorboard/'
  SAVE_MODEL_DIR: '../trained_models'
INFERENCE:
  PATH_TO_MODEL: '../trained_models/swintransformer_82/best_model.pth'
  PATH_TO_IMAGES: '../data/data_files/test'
  PATH_TO_SAVE: '../data/data_files/visualisation'
  BATCH_SIZE: 1
  SAVE_ARRAY: True
  SAVE_PNG: True

MODEL:
  NAME: "SwinTransformer"
  SWINTRANSFORMER:
    IN_CHANNELS: 1
    PRETRAINED_IN_CHANNELS: 3
    WINDOW_SIZE: 8
    IMG_SIZE: 64
    IMG_RANGE: 1.0
    DEPTHS : [6, 6, 6, 6]
    EMBED_DIM: 60
    NUM_HEADS: [6, 6, 6, 6]
    MLP_RATIO: 2
    UPSAMPLER: "pixelshuffledirect"
    RESI_CONNECTION: "1conv"
