RAW_DATA_DIR: './data/data_files/raw_data/SSurge_12600_14170_008_141120_L090HH_01_BC_s1_1x1'
TRAIN_DATA_DIR: './data/data_files/train'
DATASET:
  POLARISATION: ['HH']
  PREPROCESSING:
    DOWNSCALE_FACTOR: 2
    DECIMATION: True
    WINDOW: "hanning"
  CLIP:
    MIN: -200
    MAX: 0
  IMAGE_SIZE: [1000,3000,1000,3000]
  IN_CHANNELS: 3
  NUM_THREADS: 4
  BATCH_SIZE: 2
  VALID_RATIO: 0.2
TRAIN:
  CHECKPOINT_STEP: 5
  PRETRAINED:
    BOOL: True
    PATH: "../model_zoo/swinir/002_lightweightSR_DIV2K_s64w8_SwinIR-S_x2.pth"
    STRICT : True
  LOSS :
    NAME: "l1"
    WEIGHT: 1
  OPTIMIZER:
    NAME: Adam
    CLIPGRAD: 0
    ADAM:
      WEIGHT_DECAY: 0
      LR_INITIAL: 0.001
  SCHEDULER:
    NAME: "MultiStep"
    MULTISTEP:
      STEPS: [200000, 400000, 600000, 800000, 1000000, 2000000]
      GAMMA: 0.5
  REGULARIZER:
    ORTHSTEP: 0
    CLIPSTEP: 0
  EPOCH: 50
  TENSORBOARD_DIR: 'tensorboard/'
  SAVE_MODEL_DIR: '../trained_models'
INFERENCE:
  PATH_TO_MODEL: '../model_zoo/swinir/002_lightweightSR_DIV2K_s64w8_SwinIR-S_x2.pth'
  PATH_TO_IMAGES: '../data/data_files/test/low_resolution'
  PATH_TO_SAVE: '../data/data_files/visualisation'
  BATCH_SIZE: 1
  SAVE_ARRAY: True
  SAVE_PNG: True

MODEL:
  NAME: "SwinTransformer"
  SWINTRANSFORMER:
    IN_CHANNELS: 3
    WINDOW_SIZE: 8
    IMG_SIZE: 64
    IMG_RANGE: 200
    DEPTHS : [6, 6, 6, 6]
    EMBED_DIM: 60
    NUM_HEADS: [6, 6, 6, 6]
    MLP_RATIO: 2
    UPSAMPLER: "pixelshuffledirect"
    RESI_CONNECTION: "1conv"
