RAW_DATA_DIR: './data_files/raw_data'
TRAIN_DATA_DIR: '../data/data_files/train'
DATASET:
  FAKE_HIGH: True
  DRY_RUN: False
  POLARISATION: ['HH']
  PREPROCESSING:
    DOWNSCALE_FACTOR: 2
    DECIMATION: True
    WINDOW: "hanning"
  CLIP:
    MIN: -200
    MAX: 0
  IMAGE_SIZE: 128
  IN_CHANNELS: 1
  NUM_THREADS: 4
  BATCH_SIZE: 2
  VALID_RATIO: 0.2
TRAIN:
  CHECKPOINT_STEP: 5
  PRETRAINED:
    BOOL: False
    PATH: "../model_zoo/swinir/002_lightweightSR_DIV2K_s64w8_SwinIR-S_x2.pth"
    STRICT : False
  LOSS :
    NAME: "SSIM"
  DATA:
      MAXIFILE: "./data/dataset_maximum.npy"
      COMPUTE_MAX: False
  OPTIMIZER:
    NAME: Adam
    CLIPGRAD: 0
    ADAM:
      WEIGHT_DECAY: 0
      LR_INITIAL: 0.001
  SCHEDULER:
    NAME: "ReduceOnPlateau"
    ReduceOnPlateau:
      PATIENCE: 3
      THRESH: 1
  REGULARIZER:
    ORTHSTEP: 0
    CLIPSTEP: 0
  EPOCH: 50
  TENSORBOARD_DIR: 'tensorboard/'
  SAVE_MODEL_DIR: '../trained_models'
  NEPTUNE_API_TOKEN: 'eyJhcGlfYWRkcmVzcyI6Imh0dHBzOi8vYXBwLm5lcHR1bmUuYWkiLCJhcGlfdXJsIjoiaHR0cHM6Ly9hcHAubmVwdHVuZS5haSIsImFwaV9rZXkiOiJhNWNmZjViYS0zZDFkLTQ3ZGYtYmMzYi0yN2U1M2IxMWE0OTYifQ=='
INFERENCE:
  PATH_TO_MODEL: '../model_zoo/swinir/002_lightweightSR_DIV2K_s64w8_SwinIR-S_x2.pth'
  PATH_TO_IMAGES: '../data/data_files/test/low_resolution'
  PATH_TO_SAVE: '../data/data_files/visualisation'
  BATCH_SIZE: 1
  SAVE_ARRAY: True
  SAVE_PNG: True

MODEL:
  NAME: "SRCNN"
  SRCNN:
    BASE_CHANNELS: 32
  SRCNN2:
    BASE_CHANNELS: 64
    DEPTH: 3
  SWINTRANSFORMER:
    IN_CHANNELS: 1
    WINDOW_SIZE: 8
    IMG_SIZE: 64
    IMG_RANGE: 1
    DEPTHS : [6, 6, 6, 6]
    EMBED_DIM: 60
    NUM_HEADS: [6, 6, 6, 6]
    MLP_RATIO: 2
    UPSAMPLER: "pixelshuffledirect"
    RESI_CONNECTION: "1conv"
